Milestone 2: Ruby OOP - Tic Tac Toe
alvarorf/ruby-tic-tac-toe pull request #2
Opened 2020-09-21 20:02 UTC by alvarorf

In this pull request, we implement milestone 2 of the project: Ruby OOP - Tic Tac Toe. The purpose of this milestone was to implement the user interface of the game, such as requesting and displaying input to the user.

2020-09-21 22:30 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish with all requirements , you required to do these changes, listed below:
* [x] `[REQUIRED]` game tells which player turn it is
* [ ] `[REQUIRED]` game asks the player to select from available moves
* [x] `[REQUIRED]` game informs player if the selected move is invalid
* [ ] `[REQUIRED]` game informs player if the selected move is a winning move
* [x] `[REQUIRED]` game informs player if the selected move is a draw move
* [x] `[REQUIRED]` game repeats all actions for the next player's move

* [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
  * Inside the loop, call actions repeated for each move
  * A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:
   - This loop should  be inside `game_start` method

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

### Summary
- Remember guys your code should not work yet, that's for the next milestone, for this one you could just add as inline comments or mocking up the methods. Example
```ruby
def validMove?(player)
  value=false
  value=true if player.move
value
end
```
-  Don't forget to work with inline comments below this comment box.

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-09-22 18:06 UTC, MuriloRoque requested changes
## Status: Changes Requested :red_circle: 

### Hello @alvarorf and @kcotrinam92 :wave: 

### I am sorry, but I wasn't able to start your game (I followed instructions from your README file), it is giving me the following error below:

![Screenshot from 2020-09-22 15-05-23](https://user-images.githubusercontent.com/59691171/93920124-1fd53c00-fce5-11ea-8119-cb40d227b60c.png)


This is because of your function `game_confirmation`, which takes an argument, but when you execute it, you don't specify which argument. Also, please remove all of your commented code, I pointed them out below.

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-22 18:06 UTC, MuriloRoque commented on bin/main.rb
> +def game_confirmation(answer)
This function takes an argument, but when you call it, you don't pass that argument.

2020-09-22 18:06 UTC, MuriloRoque commented on bin/main.rb
> +      # we ask again
Please remove this commented code.

2020-09-22 18:06 UTC, MuriloRoque commented on bin/main.rb
> +      # we ask again
Please remove this commented code.

2020-09-22 18:06 UTC, MuriloRoque commented on bin/main.rb
> +  # display_board
Please remove this commented code.

2020-09-22 18:06 UTC, MuriloRoque commented on bin/main.rb
> +game_confirmation
In here, you call the function without the argument, giving me an error.

2020-09-22 18:06 UTC, MuriloRoque commented on bin/main.rb
> +  # player2 = new player(player2_name)
Please remove this commented code.

2020-09-22 18:06 UTC, MuriloRoque commented on bin/main.rb
> +  # end
Please remove this commented code.

2020-09-22 18:06 UTC, MuriloRoque commented on lib/game_logic.rb
> +# if you check according to your current position
Why do you have this whole game logic file commented?

2020-09-23 01:08 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

First of all great approach with all mockup methods 👌
However, in order to accomplish with all requirements, you required to do these changes, listed below:

- Replace while loop 
  - Work on this change and the next review certainly this assignment will be approved 
### Summary

-  Don't forget to work with inline comments below this comment box.

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-09-23 01:08 UTC, bertil291utn commented on bin/main.rb
> +  end
## Replace while loop
*  A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
  * Inside the loop, call actions repeated for each move
  * A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:
   - [ ] Replace ` while counter <= 3` for this example

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

2020-09-23 17:31 UTC, krys2fa approved these changes
# Status: Project Approved! 🥇 
Congratulations 🎊  
I am approving this milestone because you implemented the requested change (but with a minor issue). 
Please check the comment below to fully understand what was required of you by the previous TSE.

You can now merge this branch into the master branch and go on with your next milestone.

💡  Do not forget to submit your project completion form after merging this branch.

All the best team,
Chris

2020-09-23 17:31 UTC, krys2fa commented on bin/main.rb
> +    game_on = false unless counter <= 3
[] The game does not have to work perfectly in this milestone. It should show that you have thought through all scenarios though. You were asked not to use 'out-of-nowhere' numbers (ie. `counter` being between 1 and 3) and rather a terminating variable (i.e `game_on`) because the terminating variable approach is more easily understood. Doing the following would have been enough:
```
game_on = true
.....
while game_on
  ......
  if win
    game_on = false
  end
end
```
I hope this helps.

2020-09-23 17:48 UTC, merged